/* Dorax Finance — screen: Statement converter. */
// ---------- Statement converter: any bank's statement -> OFX, and the list of statements owed every month ----------
// v31 (owner): the screen belongs to no accounting platform and no bank. It was named after the one the owner uses.
function closeChip(c, a) {
  const s = c.st[a.id];
  return s === 'sent' ? `<span class="chip good"><i></i>${t('Sent')}</span>` : s === 'generated' ? `<span class="chip info"><i></i>${t('OFX ready')}</span>` : `<span class="chip ${c.days < 0 ? 'crit' : 'warn'}"><i></i>${t('Pending')}</span>`;
}
function viewConverter() {
  if (deskOnly('converter')) return deskNote('converter', true);      // on a phone this screen is left to the computer (features/phone/desk-only.js)
  const biz = needStatements(), all = convAccounts();
  if (!all.length) return `<div class="card"><div class="empty"><b>${t('Add an account first')}</b>${t('The converter needs to know which account a statement is from: its name and currency go into the OFX file.')}<div style="margin-top:10px"><button class="btn primary" data-a="account-add">${icon('plus')}${acctWord()}</button></div></div></div>`;
  // the months of the list: from the first month any account counts for (or the first one on record) up to last month, which is the one due now, plus any later month already prepared. A month nobody touched stays on the list: it is not forgotten.
  const c = UI.conv, prevYm = addMonths(ymOf(S.today), -1), known = Object.keys(S.closes), first = [...known, ...biz.map(a => a.monthlySince).filter(Boolean), prevYm].sort()[0], span = [];
  for (let ym = first; ym <= prevYm && span.length < 240; ym = addMonths(ym, 1)) span.push(ym);
  const months = [...new Set([...span, ...known])].filter(ym => needStatements(ym).length).sort().reverse(), mp = paged('months', months);
  const intro = `<section class="card" id="conv-intro"><div class="card-b" style="padding-top:20px"><div class="row" style="gap:14px 18px"><div class="grow" style="flex:1 1 320px;min-width:0"><h2 style="font-size:15px;font-weight:500">${t('Turn a bank statement into an OFX file')}</h2><p class="note" style="margin-top:4px;max-width:70ch">${t('For any bank and any accounting platform that asks for OFX. Bring the statement as CSV, Excel or PDF, check what was read, and download a file whose format was checked.')}${biz.length ? '' : ' ' + t('Do you send statements every month? After a conversion, Dorax asks whether to keep that account on a monthly list with a reminder.')}</p></div><button class="btn primary" data-a="conv-start">${icon('swap')}${t('Convert a statement')}</button></div></div></section>`;
  const checklist = !biz.length ? '' : `<section class="card"><div class="card-h"><h2>${t('Monthly statements')}</h2>${hint('convMonthly')}<span class="sub">${t('{name}: send each month’s OFX by day {d} of the next month, even when there were no movements', { name: esc(platLabel()), d: S.settings.closeDay })}</span></div>
    <div class="card-b flush"><div class="tbl-wrap"><table class="tbl"><thead><tr><th>${t('Month')}</th><th>${t('Due')}</th>${biz.map(a => `<th>${acctTag(a, true)}</th>`).join('')}</tr></thead><tbody>
    ${mp.rows.map(ym => { const ci = closeInfo(ym); return `<tr><td><b style="font-weight:500">${fmt.month(ym)}</b></td><td class="num">${fmt.date(ci.due, true)}${ci.done ? '' : ` <span class="muted">· ${dueText(ci)}</span>`}</td>
      ${biz.map(a => !owesStatement(a, ym) ? `<td class="muted">—</td>` : `<td><div class="row" style="gap:6px">${closeChip(ci, a)}${ci.st[a.id] === 'sent' ? `<button class="iconbtn" data-a="close-set" data-ym="${ym}" data-id="${a.id}" data-v="">${t('Undo')}</button>` : `<button class="btn sm" data-a="conv-start" data-ym="${ym}" data-id="${a.id}">${t('Prepare OFX')}</button><button class="iconbtn" data-a="close-set" data-ym="${ym}" data-id="${a.id}" data-v="sent">${t('Mark as sent')}</button>`}</div></td>`).join('')}</tr>`; }).join('')}
    </tbody></table></div>${mp.html}</div></section>`;
  const history = S.exports.length ? `<section class="card"><div class="card-h"><h2>${t('Export history')}</h2>${hint('convHistory')}</div><div class="card-b flush"><table class="tbl stackable"><thead><tr><th>${t('Date')}</th><th>${t('File')}</th><th>${t('Profile')}</th><th class="r">${t('Transactions')}</th></tr></thead><tbody>${paged('exports', S.exports).rows.map(e => `<tr><td class="num meta hide-sm">${fmt.date(e.date, true)}</td><td class="first"><b style="font-weight:500">${esc(e.file)}</b></td><td class="wide meta"><span class="muted">${esc(e.profile)} · ${esc(e.format)}</span></td><td class="amt">${e.count}</td></tr>`).join('')}</tbody></table>${paged('exports', S.exports).html}</div></section>` : '';
  if (!c) return `${intro}${checklist}${history}`;
  // a CSV in any layout has one more step than a recognised one: the columns are confirmed before the review
  const any = c.kind === 'csv', steps = any ? [t('Statement file'), t('Columns'), t('Review'), t('OFX file')] : [t('Statement file'), t('Review'), t('OFX file')], a = acct(c.accountId), cur = a.currency;
  const pos = any ? (c.step === 1 ? (c.mapping ? 2 : 1) : c.step + 1) : c.step;
  const head = `<div class="row"><ol class="steps">${steps.map((s, i) => `<li ${pos === i + 1 ? 'aria-current="step"' : ''} class="${pos > i + 1 ? 'done' : ''}"><b>${pos > i + 1 ? '✓' : i + 1}</b>${s}</li>`).join('')}</ol><span class="note">${esc(a.name)}${c.free && c.step === 1 ? '' : ' · ' + fmt.month(c.ym)}</span><button class="btn sm ghost spacer" data-a="conv-reset">${t('Close')}</button></div>`;
  if (c.step === 1 && c.mapping) return `${head}${convColumns(c)}`;
  if (c.step === 1) return `${head}
    ${banner('', `<b>${t('This works with your real files.')}</b> ${t('The statement you choose is read here in your browser and converted. It is not uploaded or stored anywhere.')}`)}
    <section class="card"><div class="card-h"><h2>${t('Bank statement')}</h2>${hint('convFile')}</div><div class="card-b stack" style="gap:14px">
      <p class="note">${t('Bring the statement the way your bank gives it: CSV, Excel, PDF, OFX, QIF, MT940 or CAMT.053, one file per account and currency. Any layout works: you confirm which column is the date, the description and the amount before anything is converted.')}</p>
      <div class="drop" id="drop"><div>${icon('upload')}</div><b>${c.busy ? t('Reading the file…') : c.file ? esc(c.file) : t('Drag and drop the statement here')}</b><span class="note" ${c.busy ? 'role="status"' : ''}>${c.busy ? t('Nothing is uploaded: it is read here, in your browser.') : c.needPw ? t('This PDF is protected with a password.') : c.fileNote ? esc(c.fileNote) : t('or choose a file from your device')}</span>
        <div class="row" style="justify-content:center"><label class="btn" for="stmt-file">${t('Choose file')}</label><input type="file" id="stmt-file" accept=".csv,.txt,.tsv,.xlsx,.xls,.ods,.pdf,.ofx,.qfx,.qif,.sta,.mt940,.940,.xml,.htm,.html" class="sr" data-c="conv-file"></div></div>
      ${c.needPw ? `<div class="field inline pw-row"><label for="cv-pw">${t('Password of the PDF')}</label><input type="password" id="cv-pw" autocomplete="off"><button class="btn" data-a="conv-pw">${t('Open the file')}</button><span class="note">${t('It is used to open the file here and is kept nowhere.')}</span></div>` : ''}
      ${c.error ? banner('crit', esc(c.error)) : ''}
      <div class="form-grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))">
        <div class="field"><label for="cv-acct">${t('Account')}</label><select id="cv-acct" data-c="conv-set" data-f="accountId">${acctOptions(c.accountId, null, all)}</select></div>
        <div class="field"><label for="cv-cur">${t('Currency')}</label><input type="text" id="cv-cur" value="${cur}" disabled></div>
        <div class="field"><label for="cv-profile">${t('OFX profile')}</label><select id="cv-profile" data-c="conv-set" data-f="profileId">${options(S.ofxProfiles.map(p => [p.id, p.name]), c.profileId)}</select></div></div>
      <div class="row"><span class="note">${t('The file is read here in your browser. It is not uploaded or kept.')}</span>${c.free ? '<span class="spacer"></span>' : `<button class="btn ghost spacer" data-a="conv-empty">${t('No movements this month')}</button>`}<button class="btn primary" data-a="conv-analyze" ${c.file && !c.needPw && !c.busy ? '' : 'disabled'}>${any ? t('Check the columns') : t('Read statement')}</button></div></div></section>`;
  const st = sessStats(c);
  if (c.step === 2) return `${head}
    <section class="card"><div class="card-h"><h2>${tn(st.total, '{n} transaction found', '{n} transactions found')}</h2>${hint('convReview')}<span class="sub">${esc(c.file)} · ${any ? (c.read.ids === 'column' ? t('IDs come from the “{name}” column.', { name: esc(c.csv.header[c.map.id]) }) : t('The file has no usable IDs, so Dorax makes one per transaction. The same file always gives the same IDs.')) : t('This bank’s layout is known ({name}), so there is nothing to map. Its transaction IDs become the OFX IDs.', { name: 'Wise' })}</span>${any ? `<button class="right btn sm ghost" data-a="conv-remap">${t('Change columns')}</button>` : ''}</div>
      <div class="card-b"><div class="tally"><div><b class="num">${st.verified}</b>${t('Verified')}</div><div><b class="num">${st.review}</b>${t('Needs review')}</div><div><b class="num">${st.uncertain}</b>${t('Uncertain')}</div><div><b class="num">${st.dups}</b>${t('Already in ledger')}</div></div></div>
      <div class="card-b flush" style="border-top:1px solid var(--line)">${reviewTable(c, 'conv')}</div>
      <div class="toolbar" style="border-top:1px solid var(--line);border-bottom:0"><span class="note">${st.undecided ? t('{n} rows still need a decision. Uncertain rows are never accepted automatically.', { n: st.undecided }) : t('{a} accepted · {b} ignored', { a: st.accepted, b: st.ignored }) + ' · ' + t('Net {amount}', { amount: fmt.money(sum(c.rows.filter(r => r.decision === 'accept').map(r => r.amount)), cur, { sign: true }) })}</span>
        <button class="btn primary spacer" data-a="conv-generate" ${st.undecided || (st.total && !st.accepted) ? 'disabled' : ''}>${t('Generate OFX')}</button></div></section>`;
  const p = S.ofxProfiles.find(x => x.id === c.profileId), ver = OFX_VERSIONS.find(v => v.id === p.version), ok = c.validation.ok, n = importable(c).length, sent = (S.closes[c.ym] || {})[c.accountId] === 'sent';
  return `${head}
  ${ok ? '' : banner('crit', `<b>${t('The generated OFX failed validation.')}</b> ${t('No file is available to download. Fix the failed checks below, then generate again.')}`)}
  <div class="grid g-even">
    <section class="card"><div class="card-h"><h2>${ok ? t('OFX file ready') : t('OFX not generated')}</h2>${hint('convReady')}<button class="right btn sm ghost" data-a="conv-back">${t('Back to review')}</button></div><div class="card-b stack" style="gap:14px">
      <dl class="kv"><dt>${t('Transactions exported')}</dt><dd class="num">${c.exportRows.length}</dd><dt>${t('Account')}</dt><dd>${acctTag(a, true)}</dd><dt>${t('Currency')}</dt><dd>${esc(p.currency)}${p.currency !== cur ? ` <span class="chip crit"><i></i>${t('Does not match the account')}</span>` : ''}</dd><dt>${t('Profile')}</dt><dd>${esc(p.name)}</dd><dt>${t('Account ID')}</dt><dd class="num">${esc(c.acctId || p.accountId)}${c.acctId ? ` <span class="muted">· ${t('from the file name')}</span>` : ''}</dd><dt>${t('Period')}</dt><dd class="num">${fmt.date(c.start, true)} – ${fmt.date(c.end, true)}</dd><dt>${t('Closing balance')}</dt><dd class="num">${fmt.money(c.closingUsed, cur)}</dd><dt>${t('Format')}</dt><dd>${esc(ver.label)}</dd><dt>${t('File')}</dt><dd class="mono">${esc(c.outName)}</dd></dl>
      <div class="field"><label for="cv-profile2">${t('Export with a different profile')}</label><select id="cv-profile2" data-c="conv-reprofile">${options(S.ofxProfiles.map(x => [x.id, x.name]), c.profileId)}</select></div>
      <div class="row"><button class="btn primary" data-a="conv-download" ${ok ? '' : 'disabled'}>${icon('download')}${t('Download OFX')}</button><button class="btn" data-a="conv-copy" ${ok ? '' : 'disabled'}>${icon('copy')}${t('Copy contents')}</button></div>
      ${ok && !owesStatement(a) && !a.monthlyAsked ? `<div class="ask" id="conv-ask" role="group" aria-labelledby="conv-ask-h"><b id="conv-ask-h">${t('Do you convert this account’s statement every month?')}</b>
        <p class="note">${t('If you do, Dorax keeps {name} on a monthly list: each month it shows whether the statement was converted and sent, and reminds you before the day it is due. You can change this later in the account.', { name: esc(a.name) })}</p>
        <div class="row"><button class="btn" data-a="conv-monthly" data-v="yes">${icon('check')}${t('Yes, every month')}</button><button class="btn ghost" data-a="conv-monthly" data-v="no">${t('No, just this once')}</button></div></div>` : ''}
      ${c.monthlySet ? `<div class="ask done" id="conv-ask" role="status" tabindex="-1"><b>${t('{name} is on the monthly list, starting with {month}.', { name: esc(a.name), month: fmt.month(a.monthlySince || c.ym) })}</b>
        <div class="field inline"><label for="cv-day">${t('Statements are due by day')}</label><input type="number" id="cv-day" class="day" min="1" max="28" inputmode="numeric" value="${S.settings.closeDay}" data-c="close-day"><span class="note">${t('of the following month. Use the day your accountant or accounting platform asks for.')}${biz.length > 1 ? ' ' + t('It is one day for all the accounts on the list.') : ''}</span></div>
        <p class="note">${S.user.notify.close ? t('Dorax reminds you before that day. Reminders are switched on and off in your profile.') : t('The reminder for statements is switched off in your profile.')}</p></div>` : ''}
      ${!biz.some(x => x.id === c.accountId) ? '' : `<div class="row" style="border-top:1px solid var(--line);padding-top:12px"><span class="note grow" style="flex:1 1 200px">${sent ? t('Marked as sent for {month}.', { month: fmt.month(c.ym) }) : t('After you upload it to your accounting platform, mark it as sent.')}</span>${sent ? `<span class="chip good"><i></i>${t('Sent')}</span>` : `<button class="btn" data-a="close-set" data-ym="${c.ym}" data-id="${c.accountId}" data-v="sent" ${ok ? '' : 'disabled'}>${icon('check')}${t('Mark as sent')}</button>`}</div>`}
      ${c.imported ? banner('good', `<b>${t('{n} transactions added to {name}.', { n: c.imported.imported, name: esc(a.name) })}</b> ${t('{n} already in the ledger were skipped.', { n: c.imported.duplicates })}`, 'check') : `<div class="row"><span class="note grow" style="flex:1 1 200px">${a.scope === 'business' ? t('Also keep these in the app’s company ledger? {a} new, {b} already there.', { a: n, b: st.accepted - n }) : t('Also add these to {name} in the app? {a} new, {b} already there.', { name: esc(a.name), a: n, b: st.accepted - n })}</span><button class="btn" data-a="conv-import" ${n ? '' : 'disabled'}>${t('Add {n} to ledger', { n })}</button></div>`}</div></section>
    <section class="card"><div class="card-h"><h2>${t('Validation')}</h2>${hint('convChecks')}${ok ? `<span class="chip good"><i></i>${t('All checks passed')}</span>` : `<span class="chip crit"><i></i>${t('Failed')}</span>`}</div><div class="card-b"><div class="checks">${c.validation.checks.map(k => `<div><span class="${k.ok ? 'ok' : 'bad'}" aria-hidden="true">${k.ok ? '✓' : '✕'}</span><span>${esc(k.name)}${k.detail ? ` <span class="muted">· ${esc(k.detail)}</span>` : ''}</span></div>`).join('')}</div></div></section>
  </div>
  <section class="card"><div class="card-h"><h2>${t('File preview')}</h2>${hint('convPreview')}<span class="sub">${tn(c.ofx.split('\n').length, '{n} line', '{n} lines')}</span></div><div class="card-b"><pre class="code" id="ofx-preview" tabindex="0">${esc(c.ofx)}</pre></div></section>${history}`;
}

/** Any statement: which column is what. The reader has made a first guess; the preview shows what each line becomes, so a wrong guess is seen before it is converted. */
function convColumns(c) {
  const csv = c.csv, r = convRead(c), cur = acct(c.accountId).currency, cols = csv.header.map((h, i) => [i, csv.headerless ? t('Column {n}', { n: i + 1 }) : (h || t('Column {n}', { n: i + 1 }))]), none = [[-1, t('None')]];
  const pick = (f, label, opts, extra) => `<div class="field"><label for="cm-${f}">${label}</label><select id="cm-${f}" data-c="conv-map" data-f="${f}">${options(opts, f === 'mode' || f === 'order' ? c[f] : c.map[f])}</select>${extra || ''}</div>`;
  const numeric = csv.data.some(x => /^\d{1,2}[-\/.]\d{1,2}([-\/.]\d{2,4})?$/.test((x[c.map.date] || '').split(' ')[0])), bad = `<span class="chip crit"><i></i>${t('Unreadable')}</span>`;
  // the preview shows every line as the whole file was read: a line joined to the one above, or dated by it, says so
  const byN = new Map(r.rows.map(x => [x.n, x])), prev = csv.data.map((x, n) => ({ raw: x, row: byN.get(n) || null, why: r.why[n] || '' })), pv = paged('conv-prev', prev);
  const tag = p => p.why === 'balance' ? `<span class="chip">${t('Balance line')}</span>` : p.why === 'continued' ? `<span class="chip">${t('Joined to the line above')}</span>` : p.why === 'text' ? `<span class="chip">${t('Text only')}</span>` : bad;
  const left = r.unreadable + r.texts + r.balanceLines, sep = { ';': t('semicolon'), ',': t('comma'), '\t': t('tab'), '|': t('bar') }[csv.delim];
  const from = { csv: sep ? t('separated by {sep}', { sep }) : 'CSV', xlsx: csv.sheet ? t('Excel, sheet “{name}”', { name: esc(csv.sheet) }) : 'Excel', xls: csv.sheet ? t('Excel, sheet “{name}”', { name: esc(csv.sheet) }) : 'Excel', html: 'Excel', pdf: tn(csv.pages || 1, 'PDF, {n} page', 'PDF, {n} pages'), ofx: 'OFX', qif: 'QIF', mt940: 'MT940', camt: 'CAMT.053' }[csv.source] || 'CSV';
  const lead = csv.manual ? t('Dorax could not find the table in this file by itself. If it is a statement, choose which column is the date and which is the amount; the preview shows what is read.')
    : csv.sure ? t('This kind of file names its own fields, so the columns are known. Check the preview and continue.')
    : c.kept ? t('These are the columns you confirmed for the last statement of this account. Check them against the preview.')
    : csv.source === 'pdf' ? t('A PDF is a drawing of the statement, so Dorax rebuilt its lines and columns from where the text sits on the page. Check each column against the preview.')
    : csv.headerless ? t('This file has no heading row, so the columns were found by what is in them. Check them against the preview.') : t('Dorax read the headings and made a first guess. Check each one against the preview.');
  return `<section class="card" id="conv-map"><div class="card-h"><h2>${t('Check the columns')}</h2>${hint('convCols')}<span class="sub">${esc(c.file)} · ${tn(csv.data.length, '{n} line', '{n} lines')} · ${from}${csv.skipped ? ' · ' + tn(csv.skipped, '{n} line above the table skipped', '{n} lines above the table skipped') : ''}</span><button class="right btn sm ghost" data-a="conv-map-back">${t('Back')}</button></div>
    <div class="card-b stack" style="gap:14px">
      <p class="note">${lead}</p>
      <div class="form-grid" style="grid-template-columns:repeat(auto-fit,minmax(230px,1fr))">
        ${pick('date', t('Date column'), csv.manual ? [...none, ...cols] : cols)}
        ${numeric ? pick('order', t('Dates are written'), [['dmy', t('Day / month / year')], ['mdy', t('Month / day / year')]]) : ''}
        ${csv.yearless ? `<div class="field"><label for="cm-year">${t('Year of the statement')}</label><input type="text" id="cm-year" inputmode="numeric" class="num" value="${esc(String(c.year || ''))}" data-c="conv-year" maxlength="4"></div>` : ''}
        ${pick('description', t('Description column'), [...none, ...cols])}
        ${pick('details', t('More detail column, optional'), [...none, ...cols])}
        ${pick('mode', t('Amounts are in'), [['single', t('One column')], ['split', t('Two columns: money in and money out')]])}
        ${c.mode === 'split' ? pick('credit', t('Money in column'), [...none, ...cols]) + pick('debit', t('Money out column'), [...none, ...cols]) : pick('amount', t('Amount column'), [...none, ...cols])}
        ${pick('balance', t('Balance column'), [...none, ...cols])}
        ${pick('id', t('Transaction ID column'), [[-1, t('None: Dorax makes them')], ...cols])}
        ${c.map.balance < 0 && csv.closing == null ? `<div class="field"><label for="cm-closing">${t('Closing balance ({cur}), optional', { cur })}</label><input type="text" id="cm-closing" inputmode="decimal" class="num" value="${esc(c.closingText || '')}" data-c="conv-closing" placeholder="${t('From the app’s ledger')}"></div>` : ''}</div>
      ${c.mode === 'single' ? sw('cm-invert', !!c.invert, 'conv-invert', '', t('In this file, money going out is a positive number')) : ''}
      ${csv.currency && csv.currency !== cur ? banner('warn', `<b>${t('This statement is in {a}; the account is in {b}.', { a: esc(csv.currency), b: cur })}</b> ${t('Go back and choose the account it belongs to.')}`) : ''}
      ${csv.yearless ? banner('', `<b>${t('The dates in this file have no year.')}</b> ${t('The year above is used. A statement that crosses from December into January has to be converted in two parts.')}`) : ''}
      ${numeric && !csv.orderSure ? banner('', `<b>${t('Day first or month first?')}</b> ${t('Every date in this file could be read both ways. Day first was assumed: change it above if the dates in the preview are wrong.')}`) : ''}
      ${r.rows.length && r.allPositive && c.mode === 'single' && c.map.dc < 0 ? banner('warn', `<b>${t('Every amount is a positive number.')}</b> ${t('If this file shows money going out as positive, as card statements do, switch that on above. Otherwise everything is exported as money coming in.')}`) : ''}
      ${r.chain ? (r.chain.bad ? banner('warn', `<b>${tn(r.chain.bad, '{n} balance does not follow from the line before.', '{n} balances do not follow from the line before.')}</b> ${t('Each balance should be the one before plus the movement. A column may be wrong, the sign may be reversed, or a line may be missing.')}`) : banner('good', `<b>${t('The balances add up.')}</b> ${t('Every line’s balance is the one before plus its movement, so the amounts were read as the bank wrote them.')}`, 'check')) : ''}
      ${!r.rows.length ? banner('crit', `<b>${t('No line can be read with these columns.')}</b> ${t('Check which column is the date and which is the amount.')}`) : left ? banner('', `<b>${tn(left, '{n} line is left out.', '{n} lines are left out.')}</b> ${[r.balanceLines ? tn(r.balanceLines, '{n} is a balance or total line, not a movement.', '{n} are balance or total lines, not movements.') : '', r.texts ? tn(r.texts, '{n} is text with no amount, such as a title or a note.', '{n} are text with no amount, such as titles or notes.') : '', r.unreadable ? tn(r.unreadable, '{n} has no date or no amount.', '{n} have no date or no amount.') : ''].filter(Boolean).join(' ')} ${t('They are marked in the preview.')}`) : ''}
      ${r.continued || r.dated ? `<p class="note">${[r.continued ? tn(r.continued, '{n} line of text was joined to the transaction above it.', '{n} lines of text were joined to the transaction above them.') : '', r.dated ? tn(r.dated, '{n} movement without a date took the date of the line above.', '{n} movements without a date took the date of the line above.') : ''].filter(Boolean).join(' ')}</p>` : ''}
      <div class="tbl-wrap pv-box" role="region" aria-label="${t('Preview')}"><table class="tbl" id="cm-preview"><thead><tr><th>${t('Date')}</th><th>${t('Description')}</th><th class="r">${t('Amount')}</th><th class="r hide-sm">${t('Balance')}</th><th class="hide-sm">${t('Read as')}</th></tr></thead><tbody>
        ${pv.rows.map(p => p.row ? `<tr><td class="num">${fmt.date(p.row.date, true)}</td><td>${esc(p.row.description)}</td><td class="amt">${fmt.money(p.row.amount, cur, { sign: true })}</td><td class="amt-s hide-sm">${p.row.balance === null ? '—' : fmt.money(p.row.balance, cur)}</td><td class="muted hide-sm">${p.row.amount < 0 ? t('Money out') : t('Money in')}${p.why === 'dated' ? ` <span class="chip">${t('Date from the line above')}</span>` : ''}</td></tr>`
          : `<tr class="ignored"><td class="num">${esc(p.raw[c.map.date] || '')}</td><td>${esc([p.raw[c.map.description], c.map.details >= 0 && c.map.details !== c.map.description ? p.raw[c.map.details] : ''].filter(Boolean).join(' · ') || p.raw.filter(Boolean).slice(0, 3).join(' · '))}<div class="sm-only" style="margin-top:4px">${tag(p)}</div></td><td class="amt muted">—</td><td class="amt-s muted hide-sm">—</td><td class="hide-sm">${tag(p)}</td></tr>`).join('')}</tbody></table></div>
      ${pv.html ? `<div class="pv-pager">${pv.html}</div>` : ''}
      <div class="row">${csv.headerless || csv.sure ? '' : sw('cm-remember', c.remember, 'conv-remember', '', t('Remember these columns for {name}', { name: acct(c.accountId).name }))}<span class="note spacer">${r.rows.length ? t('{a} to {b} · closing balance {c}', { a: fmt.date(r.start, true), b: fmt.date(r.end, true), c: r.closing !== null ? fmt.money(r.closing, cur) : t('not in the file') }) : ''}</span>
        <button class="btn primary" data-a="conv-map-ok" ${r.rows.length ? '' : 'disabled'}>${tn(r.rows.length, 'Continue with {n} transaction', 'Continue with {n} transactions')}</button></div></div></section>`;
}
