/* Dorax Finance — screen: Imports. */
// ---------- Imports: the side's own accounts ----------
// The way to the statement converter is on the company's side only (owner, 2026-10-09: the converter is the company's; app/shell.js HOME_HIDDEN).
// 2026-10-09 (owner: "why do I see my household's information in the Company view: transactions, import history...? The claim is that the
// accounts do not mix"): each side imports into its own accounts and lists its own imports. Before, the screen was the household's on both sides.
// The spreadsheet (plan, goals and investments) is the household's.
/** The accounts a statement can go into: the side's. */
const impAccounts = () => sideAccounts(UI.space === 'business' ? 'business' : 'personal');
/** The side's imports: into one of its accounts; one with no account (the spreadsheet) is the household's. */
const impOnSide = i => acct(i.accountId) ? isBiz(i.accountId) === (UI.space === 'business') : UI.space !== 'business';
function viewImports() {
  if (smallPhone()) return impPhone();      // a phone has its own, simpler screen (features/imports/imports.phone.js; owner, 2026-10-10)
  const imp = UI.imp;
  const hist = S.imports.filter(impOnSide);
  return `${UI.space === 'business' ? '' : sheetCard()}
  <div class="grid ${UI.space === 'business' ? 'g-3' : 'g-2'}">
    <section class="card acct"><div class="row">${icon('list')}<b style="font-weight:500">${t('CSV file')}</b></div><p class="note">${t('Any CSV statement from your bank. You say which columns are the date, the description and the amount; the app remembers it for that account.')}</p><div class="row"><label class="btn later" for="imp-file-csv">${icon('upload')}${t('Choose a CSV')}</label><input type="file" id="imp-file-csv" accept=".csv,text/csv,text/plain" class="sr" data-c="imp-file" data-source="csv"></div></section>
    <section class="card acct"><div class="row">${icon('swap')}<b style="font-weight:500">${t('OFX file')}</b></div><p class="note">${t('Uses the bank’s own transaction IDs to catch duplicates exactly.')}</p><div class="row"><label class="btn later" for="imp-file-ofx">${icon('upload')}${t('Choose an OFX')}</label><input type="file" id="imp-file-ofx" accept=".ofx,.qfx,application/x-ofx" class="sr" data-c="imp-file" data-source="ofx"></div></section>
    ${UI.space === 'business' ? `<section class="card acct"><div class="row">${icon('briefcase')}<b style="font-weight:500">${t('Statement to OFX')}</b></div><p class="note">${t('Turning a bank statement into an OFX file for an accounting platform has its own screen.')}</p><div><a class="btn" href="#converter">${t('Statement converter')}</a></div></section>` : ''}
  </div>
  ${UI.impError ? errBanner(UI.impError) : !impAccounts().length ? banner('', `<b>${t('Add an account first.')}</b> ${t('A statement is always imported into one of your accounts.')}${acctButton()}`) : `<p class="note" style="margin:0 2px">${t('Files are read here in your browser and are not uploaded. Nothing enters your ledger until you have reviewed every row.')}${S.settings.aiSuggest ? ' ' + t('With suggestions with AI on, the words of the rows you ask about are sent for a suggestion, without amounts or numbers.') : ''}</p>`}
  ${imp && imp.source !== 'bank' && (!acct(imp.accountId) || isBiz(imp.accountId) === (UI.space === 'business')) ? importPanel(imp) : ''}
  <section class="card"><div class="card-h"><h2>${t('Import history')}</h2>${hint('impHistory')}<span class="sub">${t('Every import and where its transactions went')}</span></div>
    <div class="card-b flush"><table class="tbl stackable imp-hist"><thead><tr><th class="h-date">${t('Date')}</th><th>${t('File')}</th><th class="h-acct">${t('Account')}</th><th class="r h-n h-det">${t('Detected')}</th><th class="r h-n">${t('Imported')}</th><th class="r h-n">${t('Duplicates')}</th><th class="h-st">${t('Status')}</th><th class="h-undo"><span class="sr">${t('Undo')}</span></th></tr></thead><tbody>
    ${paged('imports', hist).rows.map(i => `<tr><td class="num meta hide-sm" style="white-space:nowrap">${fmt.date(i.date, true)}</td><td class="first"><div class="tx-main"><b title="${esc(i.file)}">${esc(i.file)}</b><small>${esc(sourceLabel(i.source))}</small></div></td><td class="wide meta"><span class="muted">${esc(acct(i.accountId) ? acct(i.accountId).name : i.source === 'sheet' ? t('Plan, goals and investments') : '—')}</span><span class="sm-only muted"> · ${fmt.date(i.date, true)}</span></td>
      <td class="amt hide-sm c-det">${i.detected}</td><td class="amt" data-l="${t('Imported')}">${i.imported}</td><td class="amt wide" data-l="${t('Duplicates')}">${i.duplicates}</td><td class="wide c-st">${i.status === 'Undone' ? `<span class="chip">${t('Undone')}</span>` : `<span class="chip good"><i></i>${t('Completed')}</span>`}</td>
      <td class="r">${i.status !== 'Undone' && S.transactions.some(x => x.importId === i.id) ? `<button class="btn sm ghost" data-a="imp-undo" data-id="${i.id}">${t('Undo')}</button>` : i.status === 'Undone' ? `<span class="chip c-undone">${t('Undone')}</span>` : ''}</td></tr>`).join('') || `<tr><td colspan="8"><div class="empty"><b>${t('No imports yet')}</b>${t('Your first import will be listed here.')}</div></td></tr>`}
    </tbody></table>${paged('imports', hist).html}</div></section>`;
}
function importPanel(imp) {
  if (imp.step === 'map') {
    const need = [['date', t('Date')], ['description', t('Description')], ['amount', t('Amount')]], prev = csvRows(imp), bad = `<span class="chip crit"><i></i>${t('Unreadable')}</span>`, unread = prev.filter(r => !r.date || r.amount === null).length;
    return `<section class="card" id="imp-panel"><div class="card-h"><h2>${t('Map CSV columns')}</h2>${hint('convCols')}<span class="sub">${esc(imp.file)} · ${tn(imp.csv.rows.length, '{n} row', '{n} rows')}</span><button class="right btn sm ghost" data-a="imp-cancel">${t('Cancel')}</button></div><div class="card-b stack" style="gap:14px">
      <div class="form-grid" style="grid-template-columns:repeat(auto-fit,minmax(170px,1fr))">
        <div class="field"><label for="imp-acct">${t('Import into')}</label><select id="imp-acct" data-c="imp-account">${acctOptions(imp.accountId, null, impAccounts())}</select></div>
        ${need.map(([f, l]) => `<div class="field"><label for="map-${f}">${t('{name} column', { name: l })}</label><select id="map-${f}" data-c="imp-map" data-f="${f}">${options(imp.csv.header.map((h, i) => [i, h]), imp.map[f])}</select></div>`).join('')}</div>
      ${sw('imp-invert', !!imp.invert, 'imp-invert', '', t('In this file, purchases are positive numbers (usual in credit card statements)'))}
      ${flipNote(imp)}${cardFileHint(imp)}
      ${unread ? banner('warn', `<b>${tn(unread, '{n} row cannot be read with these columns.', '{n} rows cannot be read with these columns.')}</b> ${unread === prev.length ? t('Check which column is the date and which is the amount.') : t('They are marked below and are left out if you continue. Title or total rows usually look like this.')}`) : ''}
      <div class="tbl-wrap pv-box"><table class="tbl" id="imp-preview"><thead><tr><th>${t('Date')}</th><th>${t('Description')}</th><th class="r">${t('Amount')}</th><th>${t('Read as')}</th></tr></thead><tbody>${paged('imp-prev', prev).rows.map(r => `<tr><td class="num">${r.date ? fmt.date(r.date, true) : bad}</td><td>${esc(r.description)}</td><td class="amt">${r.amount === null ? bad : fmt.money(r.amount, acct(imp.accountId).currency, { sign: true })}</td><td class="muted">${r.amount === null ? '—' : r.amount < 0 ? t('Expense') : t('Income')}</td></tr>`).join('')}</tbody></table></div>${paged('imp-prev', prev).html ? `<div class="pv-pager">${paged('imp-prev', prev).html}</div>` : ''}
      <div class="row">${sw('imp-remember', imp.remember, 'imp-remember', '', t('Remember this mapping for {name}', { name: acct(imp.accountId).name }))}<button class="btn primary spacer" data-a="imp-review" ${unread === prev.length ? 'disabled' : ''}>${imp.rows ? t('Back to the review') : unread ? tn(prev.length - unread, 'Continue with {n} row', 'Continue with {n} rows') : t('Continue to review')}</button></div>
      ${imp.rows ? `<p class="note" style="margin:8px 0 0;text-align:right">${t('What you changed in the review is kept.')}</p>` : ''}</div></section>`;
  }
  if (imp.step === 'done') { const lr = imp.result.rules || [], shown = lr.slice(0, 3).map(([m, c]) => `${esc(m)} → ${esc(c)}`).join(', ') + (lr.length > 3 ? ' ' + t('and {n} more', { n: lr.length - 3 }) : '');      // what it learnt, so the next file needs less
    return banner('good', `<b>${t('{n} transactions imported into {name}.', { n: imp.result.imported, name: esc(acct(imp.accountId).name) })}</b> ${t('{a} duplicates skipped, {b} ignored.', { a: imp.result.duplicates, b: imp.result.ignored })} <a href="#transactions" data-a="view-account" data-id="${imp.accountId}">${t('View transactions')}</a>
      ${lr.length ? `<div class="imp-learnt">${tn(lr.length, 'Next time this goes in by itself: {list}.', 'Next time these go in by themselves: {list}.', { list: shown })} <a href="#categories" data-a="go-rules">${t('See rules')}</a></div>` : ''}`, 'check'); }
  const n = importable(imp).length, st = sessStats(imp);
  return `<section class="card" id="imp-panel"><div class="card-h"><h2>${t('Review before importing')}</h2>${hint('impReview')}<span class="sub">${esc(imp.file)} → <label class="sr" for="imp-acct">${t('Import into')}</label><select id="imp-acct" class="inline-select" data-c="imp-account">${acctOptions(imp.accountId, null, impAccounts())}</select></span>
      <span class="right row" style="gap:6px">${imp.csv ? `<button class="btn sm ghost" id="imp-back" data-a="imp-back">${icon('left')}${t('Back to the columns')}</button>` : ''}<button class="btn sm ghost" data-a="imp-cancel">${t('Cancel')}</button></span></div>
    ${imp.note ? `<div class="card-b" style="padding-bottom:0">${banner('warn', esc(imp.note))}</div>` : ''}
    ${flipNote(imp) || cardFileHint(imp) ? `<div class="card-b" style="padding-bottom:0">${flipNote(imp)}${cardFileHint(imp)}</div>` : ''}
    ${(mk => mk ? `<div class="card-b" style="padding-bottom:0">${banner('', `<b>${t('{name} is new: a savings account for the separate balance of {bank}.', { name: esc(mk.move.make), bank: esc(acct(imp.accountId).institution || acct(imp.accountId).name) })}</b> ${t('Money put into it or taken out of it moves between the two accounts: it is not income or spending.')}`)}
      <div class="field" style="max-width:280px;margin-top:10px"><label for="imp-save-bal">${t('How much is in it today? (optional)')}</label><input type="text" id="imp-save-bal" inputmode="decimal" class="num" placeholder="0,00" value="${esc(imp.saveBal || '')}" data-c="imp-save-bal"></div></div>` : '')((imp.rows || []).find(r => r.type === 'transfer' && r.move && r.move.kind === 'save' && !r.move.to))}
    ${st.dups ? `<div class="card-b" style="padding-bottom:0">${banner('warn', `<b>${tn(st.dups, '{n} transaction may already exist in this account.', '{n} transactions may already exist in this account.')}</b> ${t('They are skipped unless you choose “Keep both”.')}`)}</div>` : ''}
    <div class="card-b flush" style="padding-top:10px">${reviewTable(imp, 'imp')}</div>
    <div class="toolbar" style="border-top:1px solid var(--line);border-bottom:0"><span class="note">${st.undecided ? t('{n} rows still need a decision. Nothing is imported until every row is accepted or ignored.', { n: st.undecided }) : t('Ready: {a} to import, {b} duplicates skipped, {c} ignored.', { a: n, b: st.accepted - n, c: st.ignored })}</span>
      <button class="btn primary spacer" data-a="imp-commit" ${st.undecided || !n ? 'disabled' : ''}>${t('Import {n} transactions', { n })}</button></div></section>`;
}
