/* Dorax Finance — lists the bank logos that are in app/assets/banks/, in app/js/data/bank-logos.js.
   Run: node tools/build-banks.js (npm run banks). With --check it only says whether the list is up to date.
   It also runs by itself when the site is deployed (tools/vercel-build.js) and when the local server starts (npm start), so a logo
   that was added shows up without anything else to remember.

   Why a list: the app shows a bank's logo only when its file is there, and its colour and initials otherwise. Asking the browser for a
   file to find out would fill the console with "not found" for every bank without a logo; the list answers before any request is made.

   A file counts when its name is one of the banks' ids below and it is an .svg, .png, .webp or .jpg. Anything else in the folder is
   reported and left alone. */
const fs = require('fs'), path = require('path'), vm = require('vm');
const APP = path.join(__dirname, '..', 'app'), DIR = path.join(APP, 'assets', 'banks'), OUT = path.join(APP, 'js', 'data', 'bank-logos.js');
const KINDS = ['svg', 'png', 'webp', 'jpg'], MIME = { svg: 'image/svg+xml', png: 'image/png', webp: 'image/webp', jpg: 'image/jpeg' };

/** The banks the app knows, read from the app's own file so the two cannot disagree: { id: name }. */
function bankIds() {
  const box = { esc: s => s }; vm.createContext(box);
  vm.runInContext(fs.readFileSync(path.join(APP, 'js', 'ui', 'bank-mark.js'), 'utf8') + '\n;this.out = BANK_MARKS;', box);
  return Object.fromEntries(Object.entries(box.out).map(([name, b]) => [b.id, name]));
}
/** What is in the folder: { found: { id: 'file.ext' }, strangers: [files that are not a bank's logo] }. When a bank has two files, .svg wins. */
function scan(dir = DIR) {
  const ids = bankIds(), found = {}, strangers = [];
  for (const f of fs.existsSync(dir) ? fs.readdirSync(dir).sort() : []) {
    const m = /^(.+)\.([a-z0-9]+)$/i.exec(f), id = m && m[1].toLowerCase(), ext = m && m[2].toLowerCase().replace('jpeg', 'jpg');
    if (/^readme\.md$/i.test(f) || f.startsWith('.')) continue;
    if (!m || !ids[id] || !KINDS.includes(ext)) { strangers.push(f); continue; }
    if (!found[id] || KINDS.indexOf(ext) < KINDS.indexOf(found[id].split('.').pop().toLowerCase().replace('jpeg', 'jpg'))) found[id] = f;
  }
  return { found: Object.fromEntries(Object.entries(found).sort(([a], [b]) => a < b ? -1 : 1)), strangers, ids };      // by name, so the list does not depend on the order a computer reads a folder in
}
const fileText = found => `/* GENERATED by tools/build-banks.js from the files in app/assets/banks/. Do not edit: add or remove a logo file there, then run
   "npm run banks" (a deploy and "npm start" do it by themselves). Empty means no logo has been added yet: banks show their colour. */
const BANK_LOGOS = ${JSON.stringify(Object.fromEntries(Object.entries(found).map(([id, f]) => [id, 'assets/banks/' + f])), null, 2)};
`;
/** The same list with the pictures written into it, for the one-file preview, which has no folder beside it. */
const inlineText = (dir = DIR) => { const { found } = scan(dir); return `const BANK_LOGOS = ${JSON.stringify(Object.fromEntries(Object.entries(found).map(([id, f]) => [id, `data:${MIME[f.split('.').pop().toLowerCase().replace('jpeg', 'jpg')]};base64,` + fs.readFileSync(path.join(dir, f)).toString('base64')])))};\n`; };

/** Writes the list. quiet: say nothing unless something changed. Returns { changed, count }. */
function write(opt = {}) {
  const { found, strangers, ids } = scan(), text = fileText(found), had = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null, changed = had !== text;
  if (changed) fs.writeFileSync(OUT, text);
  if (strangers.length) console.warn(`banks: not used (the name must be a bank's id and the kind .svg, .png, .webp or .jpg): ${strangers.join(', ')}\n       ids: ${Object.keys(ids).join(', ')}`);
  if (!opt.quiet || changed) console.log(`banks: ${Object.keys(found).length} of ${Object.keys(ids).length} logos${Object.keys(found).length ? ' (' + Object.keys(found).join(', ') + ')' : ''}${changed ? ', list updated' : ''}`);
  return { changed, count: Object.keys(found).length };
}
if (require.main === module) {
  if (process.argv.includes('--check')) {
    const same = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === fileText(scan().found);
    console.log(same ? 'banks: the list of logos is up to date' : 'banks: the list of logos does not match the folder app/assets/banks/. Run "npm run banks".');
    process.exit(same ? 0 : 1);
  }
  write();
}
module.exports = { scan, write, fileText, inlineText, bankIds };
