/* Dorax Finance — screen: Settings. */
// ---------- Settings ----------
const savedChip = () => { const st = savedState(); return `<span class="chip ${st === 'failed' ? 'warn' : 'good'}"><i></i>${st === 'failed' ? t('Not saved yet') : t('Saved on the server')}</span>`; };
function viewSettings() {
  const s = S.settings;
  return `<div class="grid g-even">
  <section class="card"><div class="card-h"><h2>${t('Language and display')}</h2>${hint('setLang')}</div><div class="card-b">
    <div class="setting"><div><b style="font-weight:500">${t('Language')}</b><p>${t('Changes the interface. Your own names for categories, lines and accounts stay as you wrote them.')}</p></div><div style="min-width:190px"><label class="sr" for="set-lang">${t('Language')}</label><select id="set-lang" data-c="setting" data-k="lang">${options(LANGS, s.lang)}</select></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Appearance')}</b><p>${t('Light or dark, for the app. The home page and the login stay dark.')}</p></div><div style="min-width:190px"><label class="sr" for="set-theme">${t('Appearance')}</label><select id="set-theme" data-c="setting" data-k="theme">${options([['dark', t('Dark')], ['light', t('Light')]], s.theme === 'light' ? 'light' : 'dark')}</select></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Number and date format')}</b><p>${fmt.money(1234567, CUR)} · ${fmt.date('2026-09-02', true)}</p></div><div style="min-width:190px"><label class="sr" for="set-locale">${t('Number and date format')}</label><select id="set-locale" data-c="setting" data-k="locale">${options([['pt-BR', '1.234,56 · 02/09/2026'], ['en-US', '1,234.56 · 02 Sep 2026']], s.locale)}</select></div></div>
</div></section>
  <section class="card"><div class="card-h"><h2>${t('OFX export profiles')}</h2>${hint('setProfiles')}<button class="right btn sm" data-a="edit-profile" data-id="">${icon('plus')}${t('New profile')}</button></div><div class="card-b"><div class="list">
    ${S.ofxProfiles.map(p => `<div class="li"><div class="grow"><b style="font-weight:500">${esc(p.name)}</b> ${s.defaultProfile === p.id ? `<span class="chip">${t('Default')}</span>` : ''}<div class="note">${esc((OFX_VERSIONS.find(v => v.id === p.version) || {}).label)} · ${esc(p.currency)} · ${esc(p.accountType)} · ${t('Bank')} ${esc(p.bankId || '—')} · ${t('Account')} ${esc(p.accountId || '—')}</div></div><button class="btn sm ghost" data-a="edit-profile" data-id="${p.id}">${t('Edit')}</button></div>`).join('')}</div>
${S.ofxProfiles.length ? '' : `<div class="empty" style="padding:18px 0"><b>${t('No profile yet')}</b>${t('One is made for each account the first time you convert a statement for it.')}</div>`}
    <p class="note" style="margin-top:10px">${t('A profile is what the OFX file says about the account: the OFX version and the bank and account identifiers. One is made for each account the first time you convert a statement for it. Change it here if your accounting platform asks for something else.')}</p></div></section>
  <section class="card"><div class="card-h"><h2>${t('Import preferences')}</h2>${hint('setImport')}</div><div class="card-b">
    <div class="setting"><div><b style="font-weight:500">${t('Accounting platform')}</b><p>${t('Optional. The platform or accountant you send statements to. The name is used in reminders and on the converter screen; nothing is sent to them.')}</p></div><div style="min-width:190px"><label class="sr" for="set-platform">${t('Accounting platform')}</label><input type="text" id="set-platform" maxlength="40" autocomplete="off" value="${esc(s.platform || '')}" placeholder="${t('Its name')}" data-c="setting" data-k="platform"></div></div>
    ${S.ofxProfiles.length ? `<div class="setting"><div><b style="font-weight:500">${t('Default OFX profile')}</b><p>${t('A profile made for a new account copies its OFX version and language from this one.')}</p></div><div style="min-width:190px"><label class="sr" for="set-profile">${t('Default OFX profile')}</label><select id="set-profile" data-c="setting" data-k="defaultProfile">${options(S.ofxProfiles.map(p => [p.id, p.name]), s.defaultProfile)}</select></div></div>` : ''}
    <div class="setting"><div><b style="font-weight:500">${t('Day statements are due')}</b><p>${t('Last day of the following month to send the statements of company accounts. Ask your accounting platform or accountant which day it is.')}</p></div><div style="width:90px"><label class="sr" for="set-close">${t('Day statements are due')}</label><input type="number" id="set-close" min="1" max="28" value="${s.closeDay}" data-c="close-day"></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Accept verified rows automatically')}</b><p>${t('Verified rows start as accepted in the review table. Rows needing review and uncertain rows always wait for your decision.')}</p></div>${sw('set-auto', s.autoAcceptVerified, 'setting', 'data-k="autoAcceptVerified"')}</div></div></section>
  <section class="card" id="your-data"><div class="card-h"><h2>${t('Your data')}</h2>${hint('setData')}${savedChip()}</div><div class="card-b">
    <div class="setting"><div><b style="font-weight:500">${t('Where it is kept')}</b><p>${t('On the server, in your account. Every change is saved by itself, and it is the same on every device you log in from.')}${savedState() === 'failed' ? ' <b>' + t('The last changes have not reached the server yet. They are sent again by themselves as soon as the connection is back: keep this page open.') + '</b>' : ''}</p></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Backup')}</b><p>${t('One file with everything in this account: accounts, transactions, plan, goals, investments, rules and profiles. It can be put back into this account later.')}</p>${UI.backupError ? `<p class="err" role="alert">${esc(UI.backupError)}</p>` : ''}</div><div class="row" style="flex-wrap:wrap;justify-content:flex-end"><button class="btn" data-a="export-json">${icon('download')}${t('Download backup')}</button><label class="btn" for="backup-file">${icon('upload')}${t('Restore a backup')}</label><input type="file" id="backup-file" accept=".json,application/json" class="sr" data-c="backup-file"></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Files you bring in')}</b><p>${t('Statements and spreadsheets are read in this browser. The file itself is never uploaded or kept; only the rows you accept are saved.')}</p></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Delete all financial data')}</b><p>${t('Removes every account, transaction, import record, plan and goal from your account. Your login stays. This cannot be undone.')}</p></div><button class="btn danger" data-a="wipe">${t('Delete all data')}</button></div>
    <div class="setting"><div><b style="font-weight:500">${t('Privacy and terms')}</b><p>${t('What is kept, where, and the rules of use. Both are drafts waiting for a legal review.')}</p></div><div class="row" style="flex-wrap:wrap;justify-content:flex-end"><button class="btn" data-a="legal" data-v="privacy">${t('Privacy policy')}</button><button class="btn" data-a="legal" data-v="terms">${t('Terms of use')}</button></div></div>
    <div class="setting"><div><b style="font-weight:500">${t('Contact')}</b><p>${t('Write to Dorax. The answer comes by email.')}</p></div><button class="btn" data-a="contact">${t('Contact form')}</button></div>
</div></section>
  </div>`;
}
